id = "firrtl-source-locator"
name = "FIRRTL Source Locator"
description = "Trace FIRRTL/Chisel source locators (e.g. // @[reg.scala:255:{37,41}]) from Verilog/SystemVerilog back to Scala source locations."
version = "0.1.0"
schema_version = 1
authors = ["MrAMS <2421653893@qq.com>"]
repository = "https://github.com/MrAMS/zed-firrtl-source-locator"

[language_servers.firrtl-source-locator]
name = "FIRRTL Source Locator"
languages = ["Verilog", "SystemVerilog"]
