[package]
name = "firrtl-source-locator-server"
version = "0.1.0"
edition = "2021"
authors = ["MrAMS <2421653893@qq.com>"]
license = "MIT"

[[bin]]
name = "firrtl-source-locator-server"
path = "src/main.rs"

[dependencies]
tower-lsp = "0.20"
tokio = { version = "1.35", features = ["full"] }
